server.port=8088
spring.application.name=NOTIFICATION-SERVICE

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Review service
notification.review.base-url=http://localhost:8086

# Cloudflare R2 (S3-compatible)
r2.endpoint=https://2c63e90884e17468fd8a8dab8c0afc1f.r2.cloudflarestorage.com
r2.access-key=1DL4pRCKKmg238fsCU6i7ZYEStP9fL9o4q
r2.secret-key=fbec6c2884f59253a7868afddf5d78225bd72de64adf1d6d564249c6442fa797
r2.bucket=council-bucket
r2.region=auto
r2.public-base-url=https://pub-eee323ca044a43d2abf2d55872cc31f4.r2.dev
