server.port=8088
spring.application.name=NOTIFICATION-SERVICE

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Review service
notification.review.base-url=http://localhost:8086
notification.appointment.base-url=http://localhost:8083
notification.user.base-url=http://localhost:8084
notification.counselor.base-url=http://localhost:8090

# Cloudflare R2 (S3-compatible)
r2.endpoint=https://2c63e90884e17468fd8a8dab8c0afc1f.r2.cloudflarestorage.com
#r2.access-key=1DL4pRCKKmg238fsCU6i7ZYEStP9fL9o4q
r2.access-key=f87efc48bc9d6d364252a2a932c085af
r2.secret-key=2060bab43235d0aa24e05bcc2978666b8f12a4644e0915361a33eedb9c1b4604
r2.bucket=council-bucket
r2.region=auto
r2.public-base-url=https://pub-eee323ca044a43d2abf2d55872cc31f4.r2.dev
