# ===============================
# Server
# ===============================
server.port=8081
spring.application.name=user-authentication-service

# ===============================
# Eureka Client
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ===============================
# PostgreSQL Database
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=root

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# JWT
# ===============================
jwt.secret.key=ThisIsASuperSecureJWTSecretKeyThatIsAtLeast32Chars
jwt.expiration.ms=3600000
