server.port=8083
spring.application.name=APPOINTMENT-SERVICE

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/appointmentdb
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Downstream services
appointment.counselor.base-url=http://localhost:8090
appointment.link-generator.base-url=http://localhost:8082

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

email.kafka.topic=council-email-events

# Internal service auth
internal.jwt.secret=InternalServiceJwtSecretKeyThatIsAtLeast32Chars
internal.jwt.expiration.ms=300000

# Appointment archival to Cloudflare R2
appointments.archive.enabled=true
appointments.archive.tmp-dir=./archive
r2.endpoint=https://2c63e90884e17468fd8a8dab8c0afc1f.r2.cloudflarestorage.com
r2.access-key=f87efc48bc9d6d364252a2a932c085af
r2.secret-key=2060bab43235d0aa24e05bcc2978666b8f12a4644e0915361a33eedb9c1b4604
r2.bucket=council-bucket
r2.region=auto
r2.prefix=appointments
r2.public-base-url=https://pub-eee323ca044a43d2abf2d55872cc31f4.r2.dev
