server.port=8086
spring.application.name=REVIEW-SERVICE

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/review_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Downstream services
review.appointment.base-url=http://localhost:8083
review.notification.base-url=http://localhost:8088
